### ISSUE TITLE
reStraining run with vcf v7

### ISSUE THREAD

**Issue by luckysardar** [FelixKrueger/reStrainingOrder#2] opened 2022-03-21 16:27 UTC
Hi Felix,

Thank you for the tool I am facing problem when I am using VCF v7 (ftp://ftp-mouse.sanger.ac.uk/REL-2004-v7-SNPs_Indels/mgp_REL2005_snps_indels.vcf.gz)

 command I am using
```
./reStraining - -vcf_file  VCF_file/mgp_REL2005_snps_indels.vcf.gz  --reference_genome  GRCm38_filtered/
```
getting this below error.
```
Use of uninitialized value $fi in string eq at ./reStraining line 417, <IN> line 678340```

**Comment by FelixKrueger** [comment] 2022-03-21 22:18
I believe the Mouse Genomes Project never released a more current version of the variant data than v5, which is why reStraining works with that file out of the box. Instructions on how to download that file can be found [here](https://github.com/FelixKrueger/reStrainingOrder/tree/master/Docs#running-restraining).

I believe for the purposes of identifying different strains of mice it should be perfectly sufficient to use the v5 version (accommodating the different file format with SNPs as well as indels is quite a lot of effort (I did that for SNPsplit, but there it was much more relevant...).

**Comment by luckysardar** [comment] 2022-03-22 07:50
Hi Felix,

Thanks for your reply and concern. Problem I have is am working on JF1 strian which is not available on the v5 so I am using v7 which is having JF1 info. Can u please help me to figure it out for this version it will be very helpfull

**Comment by FelixKrueger** [comment] 2022-03-22 09:22
Hmm, but of course. I am currently reminding myself how difficult it would be to update it (looking here https://github.com/FelixKrueger/SNPsplit/issues/44)...

**Comment by luckysardar** [comment] 2022-03-22 11:24
Yeah I have seen this thread I was following the same in my analysis I have 129S1 and Jf1 strain. problem I am facing is in read assigning 10-12% reads comming from genome1 and 40-50 comming from genome2 to much difference is there so one of the thread[https://github.com/FelixKrueger/SNPsplit/issues/34] mentioned about this tool so I wanted try once please help me to figure it out what is going wrong

**Comment by FelixKrueger** [comment] 2022-03-22 12:03
I am working on it, not quite sure if I'll manage to do this today but I'll give it a try.

**Comment by luckysardar** [comment] 2022-03-22 13:24
Okay Thank you so much for you help

**Comment by FelixKrueger** [comment] 2022-03-22 14:26
I have now added a new option `--v7_VCF` that should allow you to use the v7 SNP (and INDEL) file `mgp_REL2005_snps_indels.vcf.gz`. (Note that INDEL positions, as well as positions with several different possible ALT bases are skipped).

I have been able to successfully run the following command:

```
./reStraining --vcf mgp_REL2005_snps_indels.vcf.gz --ref /bi/scratch/Genomes/Mouse/GRCm38/ --v7
```

It completed within a few minutes generating N-masking output (of chromosome 1) for all of the following strains:

```
=====================================
129P2_OlaHsd  //  129S1_SvImJ  //  129S5SvEvBrd  //  A_J  //  AKR_J  //  B10.RIII  //  BALB_cByJ  //  BALB_cJ  //  BTBR_T+_Itpr3tf_J  //  BUB_BnJ  //  C3H_HeH  //  C3H_HeJ  //  C57BL_10J  //  C57BL_10SnJ  //  C57BL_6NJ  //  C57BR_cdJ  //  C57L_J  //  C58_J  //  CAST_EiJ  //  CBA_J  //  CE_J  //  CZECHII_EiJ  //  DBA_1J  //  DBA_2J  //  FVB_NJ  //  I_LnJ  //  JF1_MsJ  //  KK_HiJ  //  LEWES_EiJ  //  LG_J  //  LP_J  //  MA_MyJ  //  MOLF_EiJ  //  NOD_ShiLtJ  //  NON_LtJ  //  NZB_B1NJ  //  NZO_HlLtJ  //  NZW_LacJ  //  PL_J  //  PWK_PhJ  //  QSi3  //  QSi5  //  RF_J  //  RIIIS_J  //  SEA_GnJ  //  SJL_J  //  SM_J  //  SPRET_EiJ  //  ST_bJ  //  SWR_J  //  WSB_EiJ  //  ZALENDE_EiJ  //  
=====================================
 ```

```
Processing chromosome 1
...
5531054 SNPs total for chromosome 1
5531054 positions on chromosome 1 were changed to 'N'
```

I hope you will be able to use the new Genome files and `MGPv7_SNP_matrix_chr1.txt.gz` matrix file as a drop in replacement for your purposes? (don't forget to index the new genome using Bowtie2 for aligning). Can you clone the current dev version and let me know how you get on?

**Comment by luckysardar** [comment] 2022-03-23 15:45
Hi Felix,

Thanks for the help I was able run it without any issues, but i am confused with my result my data is off 129S1 vs JF1 i am getting 70%129S1 and 30% for JF1 here prioviding html file [https://drive.google.com/file/d/1KZtc-xHl8MjvfYJ4jNNUqtrg_eMr4qHb/view?usp=sharing](url) can you please help me with result interpretation.

seeing my results can I say this is not pure hybrid or mapping is biased towards 129S1 


Thank you

**Comment by FelixKrueger** [comment] 2022-03-23 16:06
I would agree with the interpretation that the strain in question does not look like a clean 50/50 hybrid. Maybe more something like a 129/JF1 hybrid back-crossed to a 129 again?

While it is good to see that some contribution of JF1 seems to be found as prime candidate for your stain, I am a little confused about the fact that JF1 sometimes appears as Strain 1, sometimes as strain 2... I understand that you got corroboration that 129S1 is the primary allele using a SNPsplit approach, so the conclusion of probably correct. If you could make available a small portion of your FastQ file (say 500K reads?) I could investigate if this is simply a plotting issue? Many thanks

**Comment by luckysardar** [comment] 2022-03-23 16:21
Thanks for the help here am providing small portion of my data [https://drive.google.com/drive/folders/1L1Sj7eu8Xx-nos1LD4vQP5K2fqMnkkjM?usp=sharing](url) 

Thank you

**Comment by luckysardar** [comment] 2022-03-24 10:26
Hi felix 

I have provided the sample data above could you please help me with what is going wrong?


Thank you

**Comment by FelixKrueger** [comment] 2022-03-24 10:28
I have downloaded the data, adapted our local pipeline to work with the v7 version, and ran the pipelines for both v5 and v7 using your data. Now I need 'just' to try and make sense of it...

**Comment by FelixKrueger** [comment] 2022-03-25 21:35
OK I found it, finally! As I suspected, for the allele-ratio it always used the first strain of the in the pairwise-comparison as the one that look like the C57BL/6 reference (so both a `129S1_SvImJ/JF1_MsJ` hybrid and `JF1_MsJ/129S1_SvImJ` would both show a ~70:30 ratio allele-ratio despite the different order). This has now been corrected and comes out correctly:

**Scenario 1 (129S1_SvImJ/JF1_MsJ):**
```
Calculating hybrid strain agreement ratio for Strain1: >129S1_SvImJ< and Strain2: >JF1_MsJ<
Calculating strain ratios for Strain1: >129S1_SvImJ< and Strain2: >JF1_MsJ<

Potential Hybrid	Agreeing	Not agreeing	Percentage agreement
129S1_SvImJ/JF1_MsJ	35349	928	97.44

129S1_SvImJ/JF1_MsJ hybrid strain stats
=====================================================
Strain 129S1_SvImJ	7033 (65.7%)
Strain JF1_MsJ	3674 (34.3%)
```

**Scenario 2 (JF1_MsJ/129S1_SvImJ):**
```
Calculating hybrid strain agreement ratio for Strain1: >JF1_MsJ< and Strain2: >129S1_SvImJ<
Calculating strain ratios for Strain1: >JF1_MsJ< and Strain2: >129S1_SvImJ<

Potential Hybrid	Agreeing	Not agreeing	Percentage agreement
JF1_MsJ/129S1_SvImJ	35349	928	97.44
JF1_MsJ/129S1_SvImJ hybrid strain stats

Strain JF1_MsJ	3674 (34.3%)
Strain 129S1_SvImJ	7033 (65.7%)
```

What this means is:
1. thanks for brining this to my attention, it is good that this is now fixed
2. I am afraid in your case this doesn't have much of an impact on the allelic ratios:
   the ratio of 129S1 allele to JF1 still comes out as 2:1

I will now run another test run over night, and if it works as intended I shall make a new release soon.

**Comment by luckysardar** [comment] 2022-03-26 10:14
thanks felix for the help it will be very help full for me. this new release also applicable for SNPsplit

**Comment by FelixKrueger** [comment] 2022-03-26 12:20
There we go, this is how it should be:

<img width="1222" alt="Screenshot 2022-03-26 at 12 18 16" src="https://user-images.githubusercontent.com/5870509/160239152-1b5929b3-6057-44e6-8b42-5ef31adcc3bc.png">

And no, this should not affect SNPsplit.

**Comment by luckysardar** [comment] 2022-03-26 16:33
Hi Felix, I was getting same result in snpsplit also that's why I asked... 11-13% and 50-60% JF1 and 129s1 respectively

**Comment by FelixKrueger** [comment] 2022-03-27 19:04
The new release is now available here: https://github.com/FelixKrueger/reStrainingOrder/releases. 

All the best!

**Closed as completed by FelixKrueger** 2022-03-27 19:04 UTC
